import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '../styles/Post.module.css';

const inter = Inter({ subsets: ['latin'] });
export const runtime = 'experimental-edge';


export default function Home() {
  return (
    <>
      <Head>
        <title>Best place</title>
        <meta name="description" content="Generated by undefined team" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      

      <main>
        {/* Your main content here */}
        <iframe
                className={styles.iframe} 
                src={`${process.env.website_url}`} 
                style={{ width: '100%', height: '100vh', border: 'none' }} 
                title="Post Content"
            />
      </main>
    </>
  );
}
